### ISSUE TITLE
Portability and safety

### ISSUE THREAD

**Issue by Sierra410** [gentoo-btw/ramfetch#2]
While being a common shell, bash, is not, in fact, universal.  

Considering the simplicity of the application, I believe it is reasonable to convert the code into proper, POSIX compliant form.

Further more, to ensure that the code stays portable and safe, [shellcheck](https://github.com/marketplace/actions/shellcheck) action should be included.

**Comment by gentoo-btw** [comment]
hmm.. maybe i'll include shellcheck. i also recently merged a pull request titled "Convert the script to be more POSIX friendly"

**Comment by WhoseTheNerd** [comment]
> hmm.. maybe i'll include shellcheck. i also recently merged a pull request titled "Convert the script to be more POSIX friendly"

Use hashtags to link the issue/pull request. The pull request referenced is #1.

**Comment by gentoo-btw** [comment]
> > hmm.. maybe i'll include shellcheck. i also recently merged a pull request titled "Convert the script to be more POSIX friendly"
> 
> Use hashtags to link the issue/pull request. The pull request referenced is #1.

oh. alright.

**Comment by gentoo-btw** [comment]
> While being a common shell, bash, is not, in fact, universal.
> 
> Considering the simplicity of the application, I believe it is reasonable to convert the code into proper, POSIX compliant form.
> 
> Further more, to ensure that the code stays portable and safe, [shellcheck](https://github.com/marketplace/actions/shellcheck) action should be included.

i added shellcheck for reviewdog in my yml file. thanks for telling me about shellcheck.
