### ISSUE TITLE
Broken output with any shell

### ISSUE THREAD

**Issue by devlocalhost** [gentoo-btw/ramfetch#5]
As the title says, the output is broken in any shell (sh, bash, and fish). Changing the shebang from sh to bash fixes the issue

Screenshots with sh shebang:
![screen-171222-095915](https://user-images.githubusercontent.com/56504654/208232196-be1e2849-c523-4cfb-a20b-745aba360c1c.png)
![screen-171222-100002](https://user-images.githubusercontent.com/56504654/208232200-2707a210-edf3-4a20-9e95-0fd6d5f356e4.png)
![screen-171222-100042](https://user-images.githubusercontent.com/56504654/208232206-7a612fa8-257c-43c6-9161-d42c9f0da0f7.png)

Screenshot with bash shebang:
![Screenshot_20221217-095339](https://user-images.githubusercontent.com/56504654/208232236-8a40ac0f-da35-4392-9976-4fd2f28d6ca7.png)

**Comment by gentoo-btw** [comment]
that's weird. I never got that in my linux system.  maybe try switching up the terminal (e.g alactitty)

**Comment by devlocalhost** [comment]
> that's weird. I never got that in gentoo. maybe try switching up the terminal (e.g alactitty)
> 
> I tried ramfetch with sh on a tty and terminal (kitty). and it works fine or maybe i'll switch to `#/bin/sh` to `#/usr/bin/env bash` if it didn't solve the problem

I don't think it's the terminals fault. Happens on tty, kgx (gnome console) and termux. I'd say it's #1's fault. Neofetch for example doesn't use sh, but bash (https://github.com/dylanaraps/neofetch/blob/ccd5d9f52609bbdcd5d8fa78c4fdb0f12954125f/neofetch#L1)

**Comment by devlocalhost** [comment]
Changed the shebang to `#!/usr/bin/env bash` (like neofetch) and works. Using sh instead of bash doesn't work

**Comment by gentoo-btw** [comment]
> Changed the shebang to `#!/usr/bin/env bash` (like neofetch) and works. Using sh instead of bash doesn't work

alright. i will change it to `#!/usr/bin/env bash` then

**Comment by WhoseTheNerd** [comment]
The problem is that @gentoo-btw is using bashism in posix sh script. I created pullrequest #6 to fix this issue. Let's not forget #2 afterall.
